version: 2.1

workflows:
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+.*/
            branches:
              ignore: /.*/

jobs:
  build:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout

      - run:
          name: Install prerequisities
          command: |
            sudo pip install pylint pytest
            pip install --user -r requirements.txt

      - run:
          name: Check syntax and style
          command: |
            pylint --exit-zero --disable=invalid-name,missing-docstring,line-too-long ssm-*
            pylint --errors-only ssm-*


  publish:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run:
          name: Verify git tag vs. version
          command: |
            python setup.py verify

      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: Build packages
          command: ./build.sh

      - run:
          name: Upload to PyPI
          command: |
            twine upload dist/*
